#!/usr/bin/env python3
"""BAYCREST paket uretici.

SHA-256 manifestini yeniden uretir, surum ZIP'ini olusturur, butunlugunu
dogrular ve ZIP'ten cikarilan kopyada her iki dogrulama katmanini yeniden
calistirir. Boylece "ZIP icindeki paket gecerli mi" sorusu, depodaki calisma
kopyasindan bagimsiz olarak cevaplanir. Luau CLI bulunursa katman 3 (gercek
kaynagi sahte motorda kosturan harness) de iki kopyada calisir; bulunmazsa
atlandigi acikca yazilir. Lune bulunursa katman 4 (Studio'suz place kurulumu,
TOOLS/build_place.py) ve Open Cloud istemcisinin sahte sunucu testi
(TOOLS/test_roblox_cloud.py) de calisir. Hicbiri Roblox'a baglanmaz.

dist/ klasoru pakete girmez: ZIP'ler ve kurulan .rbxl dosyalari turetilmis
ciktidir, kaynak degildir.

K0.3 FINAL veya baska bir surum ZIP'inin uzerine YAZMAZ: hedef dosya varsa
islem durur.

Kullanim:
    python3 TOOLS/build_package.py                 # surumu config'ten turetir
    python3 TOOLS/build_package.py --out /yol/x.zip
"""
from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "PRODUCTION/PACKAGE_MANIFEST_SHA256.txt"
TOP = "BAYCREST"
EXCLUDE_DIRS = {".git", "__pycache__", ".pytest_cache"}
EXCLUDE_NAMES = {".DS_Store", "_bundle.luau"}


def package_files() -> list[Path]:
    out = []
    for p in sorted(ROOT.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        if set(rel.parts) & EXCLUDE_DIRS or rel.name in EXCLUDE_NAMES:
            continue
        if rel.parts[0] == "dist":
            continue
        if rel.suffix == ".zip":
            continue
        out.append(p)
    return out


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def version() -> str:
    cfg = (ROOT / "GAME/src/ReplicatedStorage/K0MarketConfig.lua").read_text(encoding="utf-8")
    m = re.search(r'Version\s*=\s*"([^"]+)"', cfg)
    if not m:
        raise SystemExit("config icinde Version bulunamadi")
    return m.group(1)


def write_manifest(files: list[Path]) -> int:
    lines = [
        "# BAYCREST package SHA-256 manifest",
        "# Generated by TOOLS/build_package.py; this manifest file is "
        "intentionally excluded from itself.",
    ]
    n = 0
    for p in files:
        if p == MANIFEST:
            continue
        lines.append(f"{sha256(p)}  {p.relative_to(ROOT).as_posix()}")
        n += 1
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return n


def run(cmd: list[str], cwd: Path) -> tuple[int, str]:
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return r.returncode, (r.stdout + r.stderr).strip()


TOOLS_TO_RUN = ("TOOLS/validate_package.py", "TOOLS/scenarios_k0.py", "TOOLS/run_luau_harness.py",
                "TOOLS/build_place.py", "TOOLS/test_roblox_cloud.py")
SKIP_CODE = 2  # arac calisamadi: gereken ikili dosya veya girdi yok
SKIP_REASON = {
    "TOOLS/run_luau_harness.py": "Luau CLI yok — katman 3 bu pakette kosturulmadi",
    "TOOLS/build_place.py": "Lune yok — katman 4 (place kurulumu) bu pakette kosturulmadi",
    "TOOLS/test_roblox_cloud.py": "kurulmus default place yok — Open Cloud istemci testi kosturulmadi",
}


def validate(where: Path, prefix: str) -> None:
    for tool in TOOLS_TO_RUN:
        code, txt = run([sys.executable, tool], where)
        if tool in SKIP_REASON and code == SKIP_CODE:
            print(f"  {prefix}{tool}: ATLANDI ({SKIP_REASON[tool]})")
            continue
        print(f"  {prefix}{tool}: {'PASS' if code == 0 else 'FAIL'}")
        if code != 0:
            print(txt)
            raise SystemExit(f"DURDU — {prefix or 'paketleme oncesi '}dogrulama basarisiz")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    ver = version()
    # K0-market-0.4.0 -> K0.4, K0-market-0.4.1 -> K0.4.1
    _major, minor, patch = ver.rsplit("-", 1)[-1].split(".")
    short = f"K0.{minor}" + (f".{patch}" if patch != "0" else "")
    out = args.out or (ROOT / "dist" / f"BAYCREST-{short}-PROTOTYPE.zip")

    print(f"Surum: {ver}  (paket adi {short})")
    if out.exists():
        raise SystemExit(f"DURDU — hedef zaten var, uzerine yazilmaz: {out}")
    out.parent.mkdir(parents=True, exist_ok=True)

    # 1. manifest
    files = package_files()
    n = write_manifest(files)
    files = package_files()  # manifest yeniden yazildi, hash'i degisti
    print(f"Manifest yenilendi: {n} dosya kaydi")

    # 2. dogrulama (calisma kopyasi)
    validate(ROOT, "")

    # 3. zip
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for p in files:
            z.write(p, f"{TOP}/{p.relative_to(ROOT).as_posix()}")
    size = out.stat().st_size
    print(f"ZIP yazildi: {out}  ({size / 1e6:.2f} MB, {len(files)} dosya)")

    # 4. butunluk
    with zipfile.ZipFile(out) as z:
        bad = z.testzip()
        if bad is not None:
            raise SystemExit(f"DURDU — ZIP CRC hatasi: {bad}")
        names = z.namelist()
    print(f"CRC dogrulandi: {len(names)} girdi, bozuk girdi yok")

    # 5. zip'ten cikar ve manifesti dogrula
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        with zipfile.ZipFile(out) as z:
            z.extractall(tmp)
        extracted = tmp / TOP
        mismatches = []
        checked = 0
        for line in (extracted / "PRODUCTION/PACKAGE_MANIFEST_SHA256.txt").read_text(
                encoding="utf-8").splitlines():
            if line.startswith("#") or not line.strip():
                continue
            digest, rel = line.split("  ", 1)
            f = extracted / rel
            if not f.is_file():
                mismatches.append(f"eksik: {rel}")
            elif sha256(f) != digest:
                mismatches.append(f"hash uyusmuyor: {rel}")
            checked += 1
        if mismatches:
            for m in mismatches[:10]:
                print("  " + m)
            raise SystemExit(f"DURDU — manifest dogrulamasi basarisiz ({len(mismatches)})")
        print(f"Manifest dogrulandi: {checked} dosya, sapma yok")

        # 6. cikarilan kopyada dogrulama katmanlarini yeniden calistir
        validate(extracted, "ZIP icinde ")

    print(f"\nTAMAM — {out.name} uretildi ve dogrulandi.")
    print("Bu dosya hicbir onceki surumun uzerine yazilmadi.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
